sudo: required 
language: generic
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t onurbasar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true onurbasar/react-test npm test

after_success:
  - docker build -t onurbasar/multi-client ./client
  - docker build -t onurbasar/multi-nginx ./nginx
  - docker build -t onurbasar/multi-server ./server
  - docker build -t onurbasar/multi-worker ./worker

  - docker push onurbasar/multi-client
  - docker push onurbasar/multi-nginx
  - docker push onurbasar/multi-server
  - docker push onurbasar/multi-worker

